#!/bin/bash

echo "=== DocDraft Firebase Setup ==="
echo ""

PROJECT_ID="common-project-by-aman"

echo "Firebase project: $PROJECT_ID"
echo "Web App ID: 1:663871584954:web:d40045fb0e68cf1d73a083"
echo ""

echo "=== Step 1: Enable Google Sign-In (Required) ==="
echo ""
echo "1. Open: https://console.firebase.google.com/project/$PROJECT_ID/authentication/providers"
echo "2. Click on 'Google' in the Sign-in providers list"
echo "3. Toggle it ON"
echo "4. Add your email as the Project support email"
echo "5. Click Save"
echo ""
echo "=== Step 2: Create Firestore Database ==="
echo ""
echo "1. Open: https://console.firebase.google.com/project/$PROJECT_ID/firestore"
echo "2. Click 'Create database'"
echo "3. Select 'Start in production mode'"
echo "4. Choose a location (e.g., us-central1)"
echo "5. Click 'Enable'"
echo ""
echo "=== Step 3: Deploy Security Rules ==="
echo ""
echo "Run: firebase deploy --only firestore:rules"
echo ""
echo "=== Done! ==="
echo ""
echo "Now run: npm run dev"
echo "Then open: http://localhost:3000"
